#how to run script in github playwright script
name: Playwright Tests
#on: [workflow_dispatch]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        options:
        - stage
        - qa
      browser :
        description: 'Test scenario tags'
        required: true
        default: 'chromium'
        type: choice
        options:
        - chromium
        - webkit
        - firefox
        #- all
      tags:
        description: 'Test scenario tags' #example: smoke, regression,sanity all
        required: false
        default: '@sanity'
        type: string
      testName:
        description: 'Run Test with name' #example: Link Shop, Stream
        required: false
        default: 'Link Shop'
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests from package.json file mentioned
      run: cross-env ENV=${{ github.event.inputs.environment }} npx playwright testFromGit_${{ github.event.inputs.environment }} --project ${{ github.event.inputs.browser }} -g "${{ github.event.inputs.tags }}" -g "${{ github.event.inputs.testName }}" --headed --trace on --log-level "${{ github.event.inputs.logLevel }}"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 15
